services:
  logogen:
    # Option 1: Build from current Dockerfile (recommended for development)
    build: .
    # Option 2: Use pre-built secure image (recommended for production)
    # image: logogen:secure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Mount local generated folder to container (bind mount to host filesystem)
      - ./public/generated:/app/public/generated
      # Mount local temp directory for processing
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Note: Docker volumes have been replaced with bind mounts to local filesystem
# Images will now be stored directly in ./public/generated/ on the host
# This allows immediate access to generated images without Docker volume management
